// file generated by FlutterFire CLI
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADvp2irNKpFUsE-2Ag5aqX46V1XVlcQp8',
    appId: '1:373093834758:web:316a8ee6f1635f6e12a387',
    messagingSenderId: '373093834758',
    projectId: 'info6350fianl',
    authDomain: 'info6350fianl.firebaseapp.com',
    storageBucket: 'info6350fianl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXRYwyGKnQ1NNNb_eZQklCDuDyRLJ4J5k',
    appId: '1:373093834758:android:fd7aa7d788fea89212a387',
    messagingSenderId: '373093834758',
    projectId: 'info6350fianl',
    storageBucket: 'info6350fianl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRcTmX-dPXuQww2tPcSyAmfjieWmu5yEA',
    appId: '1:373093834758:ios:ce35f1a956815cce12a387',
    messagingSenderId: '373093834758',
    projectId: 'info6350fianl',
    storageBucket: 'info6350fianl.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRcTmX-dPXuQww2tPcSyAmfjieWmu5yEA',
    appId: '1:373093834758:ios:ce35f1a956815cce12a387',
    messagingSenderId: '373093834758',
    projectId: 'info6350fianl',
    storageBucket: 'info6350fianl.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADvp2irNKpFUsE-2Ag5aqX46V1XVlcQp8',
    appId: '1:373093834758:web:9b0e5cc6616a7a2a12a387',
    messagingSenderId: '373093834758',
    projectId: 'info6350fianl',
    authDomain: 'info6350fianl.firebaseapp.com',
    storageBucket: 'info6350fianl.appspot.com',
  );
}
